# Generated by Django 4.2.7 on 2023-11-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_menuitem_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_name',
            new_name='menuName',
        ),
    ]
